# Generated by Django 3.1 on 2021-04-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20210420_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='expire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
