# Generated by Django 3.1 on 2021-04-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20210420_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignasset',
            name='release',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignasset',
            name='release_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
