# Generated by Django 3.1 on 2021-04-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20210420_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignasset',
            name='release',
            field=models.BooleanField(default=True),
        ),
    ]
