# Generated by Django 3.1 on 2021-04-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20210420_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignasset',
            name='release_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
