# Generated by Django 3.1 on 2021-04-22 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20210422_0617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['-added_on']},
        ),
        migrations.AlterModelOptions(
            name='assignasset',
            options={'ordering': ['-release_on']},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['-created_on']},
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='added_date',
            new_name='added_on',
        ),
    ]
