# Generated by Django 3.2 on 2021-05-05 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210505_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='upgraded_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
