# Generated by Django 2.2.20 on 2021-05-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_profile_upgraded_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='upgraded',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='upgraded_on',
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
