# Generated by Django 2.2.20 on 2021-05-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20210505_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='upgraded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='upgraded_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
